"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const bodyParser = require("body-parser");
const express = require("express");
const path = require("path");
const middlewares_1 = require("./middlewares");
const routes_1 = require("./routes");
const app = express();
const swaggerUi = require("swagger-ui-express");
const swaggerDocument = require("./swagger.json");
app.enable("trust proxy");
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, "public")));
app.use(middlewares_1.setContext);
app.use(middlewares_1.httpLogHandler);
app.use("/api/docs", swaggerUi.serve, swaggerUi.setup(swaggerDocument));
app.use("/api", routes_1.default);
app.use(middlewares_1.catch404);
app.use(middlewares_1.errorHandler);
exports.default = app;
