"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const controllers_1 = require("./controllers");
const router = express_1.Router();
router.get("/check", controllers_1.checkController.getCheckPage);
router.get("/", controllers_1.homeController.getHomePage);
router.get("/v1/users/", controllers_1.userController.getAll);
router.get("/v1/users/:id", controllers_1.userController.getOneById);
router.post("/v1/users/", controllers_1.userController.insertOne);
router.put("/v1/users/", controllers_1.userController.updateOne);
router.delete("/v1/users/:id", controllers_1.userController.deleteOneById);
router.get("/v1/dishes/", controllers_1.dishController.getAll);
router.get("/v1/dishes/:id", controllers_1.dishController.getOneById);
router.post("/v1/dishes/", controllers_1.dishController.insertOne);
router.put("/v1/dishes/", controllers_1.dishController.updateOne);
router.delete("/v1/dishes/:id", controllers_1.dishController.deleteOneById);
exports.default = router;
